name: Actualizar Horarios Discord

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  actualizar:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar bot
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: node index.js
